export { user, userRelations } from "./user";
export { admin } from "./admin";
export { freeCourse, freeCourseRelations } from "./free_course";
export { paidCourse, paidCourseRelations } from "./paid_course";
export { coach, coachRelations } from "./coach";
export { category, categoryRelations } from "./category";
export { order, orderRelations } from "./order";
export { user_course, userCourseRelations } from "./user_course";
export { courseType } from "./course";
export { courseStatus } from "./paid_course";
export { freeLesson, freeLessonRelations } from "./free_lesson";
export { paidLesson, paidLessonRelations } from "./paid_lesson";
